#!/bin/bash
usage='(h)ead | (p)aste | (t)ail | (w)hole : '

### CLIPBOARD TYPE
wsl_clip="clip.exe"
wayland="wl-copy"

clip=$wayland
paste="wl-paste"
###

printf '%s' "$usage"
read -r -n 1 ans
echo ""

case $ans in
h)
    head "$1" | $clip
    ;;
p)
    $paste > "$1"
    ;;
t)
    tail "$1" | $clip
    ;; 
w)
    cat "$1" | $clip 
    ;;
esac
