#!/bin/bash
usage='(b)asename | (e)xtension | (p)ath | (w)sl : '

### CLIPBOARD TYPE
wsl_clip="clip.exe"
wayland="wl-copy"

clip=$wayland
wsl_path="false"
###

real(){
    printf '%s' "$(readlink -f "$1")"
}

ext(){
    printf '%s' "$(basename "$1" | cut -d'.' -f2-)"
}

printf '%s' "$usage"
read -r -n 1 ans
echo ""

case $ans in
h)
    echo "$usage" 
    ;;
b)
    printf '%s' "$1" | $clip
    ;;
e)
    ext "$1" | $clip
    ;; 
p)
    real "$1" | $clip 
    ;;
w)
    $wsl_path -w "$(readlink -f "$1")" | $clip
    ;;
esac
