import = [
    "~/.config/alacritty/themes/rose-pine/dist/rose-pine-moon.toml"
]

[env]
TERM = "alacritty"

[font]
size = 18.0

[font.normal]
family = "Iosevka NF"
style = "Light"

[font.bold]
family = "Iosevka NF"
style = "Medium"

[font.italic]
family = "Iosevka NF"
style = "Light Italic"

[window]
decorations = "none"
dynamic_title = true
title = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
